# Generated by Django 4.2.8 on 2025-04-04 13:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import simple_history.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RegistryUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('full_name', models.CharField(max_length=255)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Instrument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tay_numero', models.CharField(blank=True, default='', max_length=100)),
                ('tuotenimi', models.CharField(blank=True, default='', max_length=100)),
                ('merkki_ja_malli', models.CharField(blank=True, default='', max_length=100)),
                ('sarjanumero', models.CharField(blank=True, default='', max_length=100)),
                ('yksikko', models.CharField(blank=True, default='', max_length=100)),
                ('kampus', models.CharField(blank=True, default='', max_length=100)),
                ('rakennus', models.CharField(blank=True, default='', max_length=100)),
                ('huone', models.CharField(blank=True, default='', max_length=100)),
                ('vastuuhenkilo', models.CharField(blank=True, default='', max_length=100)),
                ('toimituspvm', models.DateField(blank=True, null=True)),
                ('toimittaja', models.CharField(blank=True, default='', max_length=100)),
                ('lisatieto', models.CharField(blank=True, default='', max_length=100)),
                ('vanha_sijainti', models.CharField(blank=True, default='', max_length=100)),
                ('tarkistettu', models.CharField(blank=True, default='', max_length=100)),
                ('tilanne', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='HistoricalInstrument',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('tay_numero', models.CharField(blank=True, default='', max_length=100)),
                ('tuotenimi', models.CharField(blank=True, default='', max_length=100)),
                ('merkki_ja_malli', models.CharField(blank=True, default='', max_length=100)),
                ('sarjanumero', models.CharField(blank=True, default='', max_length=100)),
                ('yksikko', models.CharField(blank=True, default='', max_length=100)),
                ('kampus', models.CharField(blank=True, default='', max_length=100)),
                ('rakennus', models.CharField(blank=True, default='', max_length=100)),
                ('huone', models.CharField(blank=True, default='', max_length=100)),
                ('vastuuhenkilo', models.CharField(blank=True, default='', max_length=100)),
                ('toimituspvm', models.DateField(blank=True, null=True)),
                ('toimittaja', models.CharField(blank=True, default='', max_length=100)),
                ('lisatieto', models.CharField(blank=True, default='', max_length=100)),
                ('vanha_sijainti', models.CharField(blank=True, default='', max_length=100)),
                ('tarkistettu', models.CharField(blank=True, default='', max_length=100)),
                ('tilanne', models.CharField(max_length=100)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical instrument',
                'verbose_name_plural': 'historical instruments',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
