# Generated by Django 4.2.8 on 2025-04-08 12:51

from django.db import migrations, models
import instrument_registry.models


class Migration(migrations.Migration):

    dependencies = [
        ('instrument_registry', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InviteCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(default=instrument_registry.models.InviteCode.default_code, max_length=32)),
                ('expires', models.DateTimeField(default=instrument_registry.models.InviteCode.default_expire_time)),
            ],
        ),
    ]
