# Generated by Django 4.2.8 on 2025-04-07 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instrument_registry', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalinstrument',
            name='huoltosopimus_loppuu',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historicalinstrument',
            name='seuraava_huolto',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='instrument',
            name='huoltosopimus_loppuu',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='instrument',
            name='seuraava_huolto',
            field=models.DateField(blank=True, null=True),
        ),
    ]
