# Generated by Django 4.2.8 on 2025-04-17 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instrument_registry', '0002_historicalinstrument_huoltosopimus_loppuu_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalinstrument',
            name='edellinen_huolto',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='instrument',
            name='edellinen_huolto',
            field=models.DateField(blank=True, null=True),
        ),
    ]
