# Generated by Django 4.2.8 on 2025-04-17 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instrument_registry', '0002_invitecode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalinstrument',
            name='lisatieto',
            field=models.CharField(blank=True, default='', max_length=1000),
        ),
        migrations.AlterField(
            model_name='instrument',
            name='lisatieto',
            field=models.CharField(blank=True, default='', max_length=1000),
        ),
    ]
