# Generated by Django 4.2.8 on 2025-04-27 11:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('instrument_registry', '0003_alter_historicalinstrument_lisatieto_and_more'),
        ('instrument_registry', '0003_historicalinstrument_edellinen_huolto_and_more'),
    ]

    operations = [
    ]
