# Generated by Django 4.2.8 on 2025-10-22 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instrument_registry', '0005_registryuser_groups_registryuser_is_active_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalinstrument',
            name='history_username',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
