# Generated by Django 4.2.8 on 2025-10-23 15:43

from django.db import migrations, models
import pgvector.django.vector


class Migration(migrations.Migration):

    dependencies = [
        ('instrument_registry', '0007_pgvector_extension'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalinstrument',
            name='tuotenimi_en',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='instrument',
            name='embedding_en',
            field=pgvector.django.vector.VectorField(blank=True, dimensions=384, null=True),
        ),
        migrations.AddField(
            model_name='instrument',
            name='embedding_fi',
            field=pgvector.django.vector.VectorField(blank=True, dimensions=768, null=True),
        ),
        migrations.AddField(
            model_name='instrument',
            name='tuotenimi_en',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
