# Generated by Django 4.2.8 on 2025-10-27 18:39

from django.db import migrations
import pgvector.django.vector


class Migration(migrations.Migration):

    dependencies = [
        ('instrument_registry', '0008_historicalinstrument_tuotenimi_en_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instrument',
            name='embedding_en',
            field=pgvector.django.vector.VectorField(blank=True, dimensions=768, null=True),
        ),
    ]
