# Generated by Django 4.2.8 on 2025-11-01 22:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('instrument_registry', '0009_alter_instrument_embedding_en'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='instrument',
            name='embedding_fi',
        ),
    ]
