# Generated by Django 4.2.8 on 2025-12-24 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instrument_registry', '0012_historicalinstrumentattachment'),
    ]

    operations = [
        migrations.AddField(
            model_name='instrument',
            name='enriched_description',
            field=models.TextField(blank=True, default='', max_length=400),
        ),
    ]
